"""
Unit tests for User model.

Following TDD principles - test written before implementation.
"""
from datetime import datetime

import pytest
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from mybudget.models.user import User


@pytest.mark.unit
class TestUserModel:
    """Unit tests for User model."""

    def test_user_creation(self) -> None:
        """Test creating a User instance with required fields."""
        user = User(
            email="test@example.com",
            password_hash="hashed_password_here",
            timezone="Europe/Brussels",
        )

        assert user.email == "test@example.com"
        assert user.password_hash == "hashed_password_here"
        assert user.timezone == "Europe/Brussels"
        # ID is None until inserted to database (generated by DB)
        # After insert, the UUID will be set

    @pytest.mark.asyncio
    async def test_user_default_timezone_on_insert(
        self, db_session: AsyncSession
    ) -> None:
        """Test that default timezone is UTC when inserted to database."""
        user = User(email="test@example.com", password_hash="hashed_password")

        db_session.add(user)
        await db_session.flush()  # Flush to get defaults

        assert user.timezone == "UTC"

    @pytest.mark.asyncio
    async def test_user_timestamps_auto_generated_on_insert(
        self, db_session: AsyncSession
    ) -> None:
        """Test that created_at and updated_at are auto-generated on insert."""
        user = User(
            email="timestamps@example.com",
            password_hash="hashed_password",
            timezone="UTC",
        )

        db_session.add(user)
        await db_session.flush()

        assert user.created_at is not None
        assert user.updated_at is not None
        assert isinstance(user.created_at, datetime)
        assert isinstance(user.updated_at, datetime)

    def test_user_repr_does_not_expose_password(self) -> None:
        """Test that __repr__ doesn't expose password hash."""
        user = User(
            email="test@example.com",
            password_hash="secret_hash",
            timezone="Europe/Brussels",
        )

        repr_str = repr(user)
        assert "test@example.com" in repr_str
        assert "secret_hash" not in repr_str
        assert "password" not in repr_str.lower()

    @pytest.mark.asyncio
    async def test_user_persistence(self, db_session: AsyncSession) -> None:
        """Test that User can be persisted to database."""
        user = User(
            email="persist@example.com",
            password_hash="hashed_password",
            timezone="America/New_York",
        )

        db_session.add(user)
        await db_session.commit()
        await db_session.refresh(user)

        # Query the user back
        stmt = select(User).where(User.email == "persist@example.com")
        result = await db_session.execute(stmt)
        retrieved_user = result.scalar_one()

        assert retrieved_user.id == user.id
        assert retrieved_user.email == "persist@example.com"
        assert retrieved_user.password_hash == "hashed_password"
        assert retrieved_user.timezone == "America/New_York"

    @pytest.mark.asyncio
    async def test_user_email_uniqueness(self, db_session: AsyncSession) -> None:
        """Test that email must be unique (database constraint)."""
        user1 = User(email="unique@example.com", password_hash="hash1")
        user2 = User(email="unique@example.com", password_hash="hash2")

        db_session.add(user1)
        await db_session.commit()

        db_session.add(user2)
        with pytest.raises(IntegrityError):
            await db_session.commit()

    @pytest.mark.asyncio
    async def test_user_updated_at_changes_on_update(
        self, db_session: AsyncSession
    ) -> None:
        """Test that updated_at timestamp changes when user is updated."""
        user = User(email="update@example.com", password_hash="initial_hash")

        db_session.add(user)
        await db_session.commit()
        await db_session.refresh(user)

        original_updated_at = user.updated_at

        # Update the user
        user.timezone = "Asia/Tokyo"
        await db_session.commit()
        await db_session.refresh(user)

        assert user.updated_at > original_updated_at
