"""add_sync_status_and_categorization_fields

Revision ID: 70aa4b75ad8e
Revises: 378a7242baff
Create Date: 2026-01-18 08:35:55.862558

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "70aa4b75ad8e"
down_revision = "378a7242baff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    sync_status_enum = postgresql.ENUM(
        "SUCCESS", "FAILED", "PENDING", "NEVER_SYNCED", name="sync_status", create_type=False
    )
    sync_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "accounts",
        sa.Column(
            "sync_status",
            sync_status_enum,
            nullable=False,
            server_default="NEVER_SYNCED",
        ),
    )
    op.add_column("accounts", sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("accounts", sa.Column("sync_error", sa.String(length=500), nullable=True))
    # Create categorization_source enum
    categorization_source_enum = postgresql.ENUM(
        "MANUAL", "RULE", "ML_SUGGESTED", name="categorization_source", create_type=False
    )
    categorization_source_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "transactions",
        sa.Column(
            "categorization_source",
            categorization_source_enum,
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("confidence_score", sa.Numeric(precision=3, scale=2), nullable=True),
    )
    op.create_index(
        op.f("ix_transactions_categorization_source"),
        "transactions",
        ["categorization_source"],
        unique=False,
    )
    # Add check constraint for confidence_score range
    op.create_check_constraint(
        "ck_transactions_confidence_score_range",
        "transactions",
        "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraint first
    op.drop_constraint("ck_transactions_confidence_score_range", "transactions", type_="check")
    op.drop_index(op.f("ix_transactions_categorization_source"), table_name="transactions")
    op.drop_column("transactions", "confidence_score")
    op.drop_column("transactions", "categorization_source")
    op.drop_column("accounts", "sync_error")
    op.drop_column("accounts", "last_sync_at")
    op.drop_column("accounts", "sync_status")

    # Drop enum types
    postgresql.ENUM(name="categorization_source").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="sync_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
