"""add_reconciliations_table

Revision ID: 378a7242baff
Revises: 61caa0fb8762
Create Date: 2026-01-17 12:13:31.262985

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "378a7242baff"
down_revision = "61caa0fb8762"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("statement_balance", sa.Numeric(precision=19, scale=4), nullable=False),
        sa.Column("statement_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("IN_PROGRESS", "COMPLETED", name="reconciliation_status"),
            nullable=False,
        ),
        sa.Column("adjustment_transaction_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_reconciliations_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_transaction_id"],
            ["transactions.id"],
            name=op.f("fk_reconciliations_adjustment_transaction_id_transactions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reconciliations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliations")),
    )
    op.create_index(
        op.f("ix_reconciliations_account_id"), "reconciliations", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliations_user_id"), "reconciliations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reconciliations_user_id"), table_name="reconciliations")
    op.drop_index(op.f("ix_reconciliations_account_id"), table_name="reconciliations")
    op.drop_table("reconciliations")
    # ### end Alembic commands ###
