"""add bank connection models

Revision ID: f22b41e7cbb7
Revises: 70aa4b75ad8e
Create Date: 2026-01-19 19:40:31.577756

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f22b41e7cbb7"
down_revision = "70aa4b75ad8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_connections",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_connection_id", sa.String(length=255), nullable=False),
        sa.Column("institution_id", sa.String(length=100), nullable=False),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "ACTIVE",
                "NEEDS_ATTENTION",
                "ERROR",
                "DISCONNECTED",
                name="bank_connection_status",
            ),
            nullable=False,
        ),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_bank_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_connections")),
    )
    op.create_index(
        op.f("ix_bank_connections_user_id"), "bank_connections", ["user_id"], unique=False
    )
    op.create_table(
        "linked_accounts",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("provider_account_id", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("account_number_masked", sa.String(length=50), nullable=True),
        sa.Column(
            "account_type",
            postgresql.ENUM("CHECKING", "SAVINGS", "CREDIT", name="linked_account_type"),
            nullable=True,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance", sa.Numeric(precision=19, scale=4), nullable=True),
        sa.Column("balance_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_linked_accounts_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["bank_connections.id"],
            name=op.f("fk_linked_accounts_connection_id_bank_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_linked_accounts")),
    )
    op.create_index(
        op.f("ix_linked_accounts_connection_id"), "linked_accounts", ["connection_id"], unique=False
    )
    op.create_table(
        "sync_jobs",
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("linked_account_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "RUNNING", "COMPLETED", "FAILED", name="sync_job_status"),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            postgresql.ENUM("SCHEDULED", "MANUAL", "INITIAL", name="sync_trigger_type"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transactions_fetched", sa.Integer(), nullable=False),
        sa.Column("transactions_imported", sa.Integer(), nullable=False),
        sa.Column("transactions_duplicates", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["bank_connections.id"],
            name=op.f("fk_sync_jobs_connection_id_bank_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["linked_account_id"],
            ["linked_accounts.id"],
            name=op.f("fk_sync_jobs_linked_account_id_linked_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_jobs")),
    )
    op.create_index(
        op.f("ix_sync_jobs_connection_id"), "sync_jobs", ["connection_id"], unique=False
    )
    op.alter_column(
        "accounts",
        "sync_status",
        existing_type=postgresql.ENUM(
            "SUCCESS", "FAILED", "PENDING", "NEVER_SYNCED", name="sync_status"
        ),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts",
        "sync_status",
        existing_type=postgresql.ENUM(
            "SUCCESS", "FAILED", "PENDING", "NEVER_SYNCED", name="sync_status"
        ),
        server_default=sa.text("'NEVER_SYNCED'::sync_status"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_sync_jobs_connection_id"), table_name="sync_jobs")
    op.drop_table("sync_jobs")
    op.drop_index(op.f("ix_linked_accounts_connection_id"), table_name="linked_accounts")
    op.drop_table("linked_accounts")
    op.drop_index(op.f("ix_bank_connections_user_id"), table_name="bank_connections")
    op.drop_table("bank_connections")
    # ### end Alembic commands ###
