"""add_transaction_bank_sync_fields

Revision ID: efa068ae05db
Revises: f22b41e7cbb7
Create Date: 2026-01-20 05:48:37.829753

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "efa068ae05db"
down_revision = "f22b41e7cbb7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column("transactions", sa.Column("import_source", sa.String(length=50), nullable=True))
    op.add_column("transactions", sa.Column("import_batch_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_transactions_external_id"), "transactions", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_import_batch_id"), "transactions", ["import_batch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_import_batch_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_external_id"), table_name="transactions")
    op.drop_column("transactions", "import_batch_id")
    op.drop_column("transactions", "import_source")
    op.drop_column("transactions", "external_id")
    # ### end Alembic commands ###
