"""add_assignments_table

Revision ID: d80c2293d473
Revises: 3506b8c7ea9f
Create Date: 2026-01-17 10:27:18.483176

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d80c2293d473"
down_revision = "3506b8c7ea9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_assignments_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assignments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    op.create_index(
        "idx_assignments_category_month", "assignments", ["category_id", "month"], unique=False
    )
    op.create_index(
        op.f("ix_assignments_category_id"), "assignments", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_assignments_month"), "assignments", ["month"], unique=False)
    op.create_index(op.f("ix_assignments_user_id"), "assignments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assignments_user_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_month"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_category_id"), table_name="assignments")
    op.drop_index("idx_assignments_category_month", table_name="assignments")
    op.drop_table("assignments")
    # ### end Alembic commands ###
