"""add_category_targets_table

Revision ID: 61caa0fb8762
Revises: d80c2293d473
Create Date: 2026-01-17 10:55:07.278830

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "61caa0fb8762"
down_revision = "d80c2293d473"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_targets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column(
            "target_type",
            postgresql.ENUM(
                "MONTHLY_NEEDED", "TARGET_BALANCE", "TARGET_BY_DATE", name="target_type"
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "(target_type = 'TARGET_BY_DATE' AND target_date IS NOT NULL) OR (target_type != 'TARGET_BY_DATE' AND target_date IS NULL)",
            name=op.f("ck_category_targets_check_target_date_constraint"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_category_targets_check_positive_amount")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_targets_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_category_targets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_targets")),
    )
    op.create_index(
        op.f("ix_category_targets_category_id"), "category_targets", ["category_id"], unique=True
    )
    op.create_index(
        op.f("ix_category_targets_user_id"), "category_targets", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_targets_user_id"), table_name="category_targets")
    op.drop_index(op.f("ix_category_targets_category_id"), table_name="category_targets")
    op.drop_table("category_targets")
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS target_type")
    # ### end Alembic commands ###
